language: go

go:
  - 1.9.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

install:
  - go get  github.com/PuerkitoBio/goquery
  - go get	github.com/andybalholm/cascadia
  - go get	github.com/antchfx/htmlquery
  - go get	golang.org/x/net